### ISSUE TITLE
JavaScript error and crash when a Prolog exception is expected

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#164]
I frequently get the following JavaScript error and crash when a Prolog exception is expected:

```text
/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2171
			var app = this.args[i].apply(subs);
			                       ^

TypeError: this.args[i].apply is not a function
    at Term.apply (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2171:27)
    at Term.apply (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2171:27)
    at Object.unify (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:4425:30)
    at Thread.step (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2836:20)
    at Thread.again (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2921:13)
    at Object.callback (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5034:12)
    at Thread.again (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2936:13)
    at Thread.answer (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2881:8)
    at catch/3 (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5036:12)
    at Thread.step (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2823:13)
```

Does this stack trace gives enough hints on the bug?

**Comment by pmoura** [comment]
This crash happens notably anytime there's an instantiation error in an arithmetic expression that's being evaluated.

**Comment by jariazavalverde** [comment]
I can't reproduce this error. Do you know any specific goal for which it fails? If not, it would also help me to know how to reproduce the error using Logtalk.

**Comment by pmoura** [comment]
Thanks for looking into it. Try e.g. `X is sin(_).` or something a bit more complex: `X is sin(abs(3 + _)).`.

**Comment by jariazavalverde** [comment]
I am not getting any error with the latest version. Maybe it has been fixed with the recent PRs?

![error](https://user-images.githubusercontent.com/5055295/89797095-cb0da580-db2a-11ea-9b58-f7925d70448f.png)

**Comment by pmoura** [comment]
In the particular case of my pull requests, none addressed this issue. Did you also tried with a predicate definition in a consulted file that calls one of those test goals? That was the context where the crash happened when I report this issue.

**Comment by pmoura** [comment]
I can still reproduce the crash using the `abs/1` arithmetic function tests:

```text
$ export NODE_PATH=/Users/pmoura/Documents/Logtalk/tp/node_modules
$ taulgt 
...
?- {tester}.
% 
% tests started at 0(-)00(-)00(,) 00(:)00(:)00
% 
% running tests from object tests
% file(:) (/)Users(/)pmoura(/)Documents(/)Logtalk(/)logtalk3(/)tests(/)prolog(/)functions(/)abs_1(/)tests.lgt
% 
% iso_abs_1_01(:) success
% iso_abs_1_02(:) success
% iso_abs_1_03(:) success
% iso_abs_1_04(:) success
/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2176
			var app = this.args[i].apply(subs);
			                       ^

TypeError: this.args[i].apply is not a function
    at Term.apply (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2176:27)
    at Term.apply (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2176:27)
    at Object.unify (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:4431:30)
    at Thread.step (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2841:20)
    at Thread.again (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2927:13)
    at Object.callback (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5052:12)
    at Thread.again (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2942:13)
    at Thread.answer (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2887:8)
    at catch/3 (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5054:12)
    at Thread.step (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2828:13)
```

**Comment by pmoura** [comment]
But I got a detail wrong. The crash happens with a non-evaluable argument to an arithmetic function. However, I have been unable so far to reduce the crash to a minimal example. The error may be instead on the propagation of the exception.
